# Generated by Django 6.0.7 on 2026-08-20 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('runbooks', '0003_rename_retrieval_engine_runbookrecommendation_retrieval_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current state of the human approval workflow', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Notes for approval or reason for rejection')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was approved or rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='The incident ticket associated with this approval request', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='incidents.incident')),
                ('requested_by', models.ForeignKey(help_text='The IT Admin who requested approval', on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The IT Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('runbook', models.ForeignKey(help_text='The recommended runbook procedure to be approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='runbooks.runbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
