# Generated by Django 6.0.7 on 2026-08-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(help_text='Predefined action hook name being executed', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('output', models.TextField(blank=True, help_text='Standard output from simulated execution')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed or was blocked')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the execution completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.OneToOneField(help_text='The approval request this execution record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='automation.automationapproval')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
