# Generated by Django 6.0.7 on 2026-09-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed')], help_text='Outcome of the simulated verification check', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Detailed output message from the verification simulation')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when verification was performed')),
                ('execution', models.OneToOneField(help_text='The automation execution record being verified', on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='automation.automationexecution')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
