# Generated by Django 6.0.7 on 2026-09-27 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_verificationresult'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INCIDENT_CREATED', 'Incident Created'), ('AI_ANALYSIS_COMPLETED', 'AI Analysis Completed'), ('RUNBOOK_RECOMMENDED', 'Runbook Recommended'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVAL_APPROVED', 'Approval Approved'), ('APPROVAL_REJECTED', 'Approval Rejected'), ('AUTOMATION_STARTED', 'Automation Started'), ('AUTOMATION_COMPLETED', 'Automation Completed'), ('AUTOMATION_FAILED', 'Automation Failed'), ('AUTOMATION_BLOCKED', 'Automation Blocked'), ('VERIFICATION_STARTED', 'Verification Started'), ('VERIFICATION_PASSED', 'Verification Passed'), ('VERIFICATION_FAILED', 'Verification Failed'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_ESCALATED', 'Incident Escalated')], help_text='Type of audit event', max_length=50)),
                ('message', models.TextField(help_text='Human-readable audit message describing what occurred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured event metadata (e.g., match score, action name, error reason)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the audit log entry was generated')),
                ('actor', models.ForeignKey(blank=True, help_text='The user who triggered this event (or NULL for automated system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='The incident ticket associated with this audit entry', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
