# Generated by Django 6.0.7 on 2026-08-03 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(editable=False, help_text='Automatically generated unique identifier', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Brief title of the incident', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('category', models.CharField(choices=[('SERVER', 'Server'), ('DATABASE', 'Database'), ('NETWORK', 'Network'), ('APPLICATION', 'Application'), ('STORAGE', 'Storage'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ANALYZING', 'Analyzing'), ('RECOMMENDATION_READY', 'Recommendation Ready'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_activities', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
