# Generated by Django 6.0.7 on 2026-09-29 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='classification_method',
            field=models.CharField(blank=True, default='Rule-based local classification', help_text='Triage classification algorithm description', max_length=80),
        ),
        migrations.AddField(
            model_name='incident',
            name='classified_priority',
            field=models.CharField(blank=True, default='P3', help_text='Suggested triage priority (P1, P2, P3, P4)', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='intent',
            field=models.CharField(blank=True, default='Unknown', help_text='Normalized intent classification (e.g. Service Degradation)', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='normalized_description',
            field=models.TextField(blank=True, default='', help_text='Deterministic normalized problem description'),
        ),
        migrations.AddField(
            model_name='incident',
            name='service',
            field=models.CharField(blank=True, default='Unknown', help_text='Classified infrastructure service (e.g. Web Server)', max_length=50),
        ),
        migrations.CreateModel(
            name='IncidentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], help_text='Runbook usefulness rating (1-5)')),
                ('comment', models.TextField(blank=True, help_text='Suggestions or comments on runbook improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(help_text='The incident ticket this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='incidents.incident')),
                ('user', models.ForeignKey(help_text='Employee who provided feedback', on_delete=django.db.models.deletion.CASCADE, related_name='incident_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
