# Generated by Django 6.0.7 on 2026-08-10 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runbook_number', models.CharField(editable=False, help_text='Automatically generated unique identifier', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Brief title of the runbook', max_length=200)),
                ('description', models.TextField(help_text='A clear description of what problem the runbook solves')),
                ('category', models.CharField(choices=[('SERVER', 'Server'), ('DATABASE', 'Database'), ('NETWORK', 'Network'), ('APPLICATION', 'Application'), ('STORAGE', 'Storage'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='OTHER', help_text='Service category this runbook applies to', max_length=20)),
                ('symptoms', models.TextField(help_text='Symptoms or conditions under which this runbook should be used')),
                ('steps', models.TextField(help_text='Step-by-step troubleshooting or resolution procedure')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('automation_action', models.CharField(blank=True, help_text='Associated automation action (metadata only)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate rather than delete runbooks to preserve history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
