# Generated by Django 6.0.7 on 2026-08-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('runbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunbookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Semantic matching similarity score')),
                ('retrieval_engine', models.CharField(default='tfidf', help_text='Algorithm identifier used to generate match scores', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(help_text='The incident ticket this recommendation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='runbook_recommendation', to='incidents.incident')),
                ('runbook', models.ForeignKey(blank=True, help_text='The recommended runbook procedure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='runbooks.runbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
