# Generated by Django 6.0.7 on 2026-08-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runbooks', '0002_runbookrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runbookrecommendation',
            old_name='retrieval_engine',
            new_name='retrieval_method',
        ),
    ]
