# Generated by Django 6.0.7 on 2026-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbooks', '0003_rename_retrieval_engine_runbookrecommendation_retrieval_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='runbookrecommendation',
            name='citation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured citation and evidence metadata'),
        ),
    ]
